apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-project-deployment
  labels:
    app: final-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: final-project
  template:
    metadata:
      labels:
        app: final-project
    spec:
      containers:
      - name: final-project-container
        image: eve56/final-project:latest
        ports:
        - containerPort: 80
